apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-only-binding
subjects:
- kind: Group
  name: read-only-group # This MUST match the group in your aws-auth ConfigMap
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: read-only-role # This MUST match the role you created above
  apiGroup: rbac.authorization.k8s.io
